[package]
name = "qselect"
version = "0.1.0"
authors = ["Jason Dusek <jason.dusek@gmail.com>"]

[lib]
name = "qselect"
crate-type = ["lib", "cdylib"]

[dependencies]
error-chain = "*"
libc = "*"
linked-hash-map = "^0.3"
