[package]
name = "qselect"
version = "0.1.0"
authors = ["Jason Dusek <jason.dusek@gmail.com>"]
build = "build.rs"

[lib]
name = "qselect"
crate-type = ["lib", "cdylib"]

[dependencies]
error-chain = "*"
libc = "^0.2"
linked-hash-map = "^0.3"

[build-dependencies]
rusty-cheddar = "^0.3"